import { Peer } from "../peer";
import { PeerStatus } from "../types";
import { ZeroHubClient } from "../zeroHub";
import { Topology } from ".";
import { setupDataChannel, setupMediaChannel } from "./peerSetup";

/**
 * SFUTopology implements a Selective Forwarding Unit topology.
 * In this topology, there is one designated peer (the SFU) that receives streams from all other peers
 * and forwards them selectively. This is more scalable than mesh topology for larger groups.
 * The SFU peer is typically the first peer to join the hub or can be explicitly designated.
 *
 * Benefits:
 * - More scalable than mesh topology (reduces bandwidth usage for clients)
 * - Better for larger groups (5+ participants)
 * - Lower CPU usage on client devices
 *
 * Trade-offs:
 * - Requires one peer to act as the SFU (higher bandwidth/CPU for that peer)
 * - Single point of failure if the SFU peer disconnects
 *
 * @typeParam PeerMetadata - The type of metadata associated with the peer.
 * @typeParam HubMetadata - The type of metadata associated with the hub.
 */
export class SFUTopology<PeerMetadata = object, HubMetadata = object>
  implements Topology<PeerMetadata, HubMetadata>
{
  /**
   * The ZeroHub client instance.
   * This is initialized in the init method and used to manage peer connections.
   */
  zeroHub: ZeroHubClient<PeerMetadata, HubMetadata> | undefined;

  /**
   * The ID of the peer acting as the SFU.
   * If not set, the first peer in the hub becomes the SFU.
   */
  private sfuPeerId: string | undefined;

  /**
   * Creates a new SFU topology instance.
   *
   * @param sfuPeerId - Optional: explicitly set which peer should act as the SFU.
   *                    If not provided, the first peer to join becomes the SFU.
   */
  constructor(sfuPeerId?: string) {
    this.sfuPeerId = sfuPeerId;
  }

  init(zeroHub: ZeroHubClient<PeerMetadata, HubMetadata>) {
    this.zeroHub = zeroHub;
  }

  /**
   * Returns the numerically lowest peer ID from the given IDs.
   * Peer IDs are sequential decimal strings generated by the server
   * ("1", "2", ..., "10", ...), so they must be compared numerically —
   * a lexicographic sort would pick "10" over "2".
   *
   * @param peerIds - Peer IDs to compare (mutated in place, so pass a copy).
   * @returns The lowest peer ID.
   */
  private lowestPeerId(peerIds: string[]): string {
    return peerIds
      .sort((a, b) => parseInt(a, 10) - parseInt(b, 10))
      .shift() as string;
  }

  /**
   * Determines if the current peer is the SFU.
   *
   * @returns True if this peer is the SFU, false otherwise.
   */
  private isSFU(): boolean {
    if (!this.zeroHub || !this.zeroHub.myPeerId) {
      return false;
    }

    // If SFU peer ID is explicitly set, check against it
    if (this.sfuPeerId) {
      return this.zeroHub.myPeerId === this.sfuPeerId;
    }

    // Otherwise, the peer with the lowest ID becomes the SFU
    const allPeerIds = Object.keys(this.zeroHub.peers);
    if (allPeerIds.length === 0) {
      return true; // First peer is always the SFU
    }

    const lowestPeerId = this.lowestPeerId([
      this.zeroHub.myPeerId,
      ...allPeerIds,
    ]);
    return this.zeroHub.myPeerId === lowestPeerId;
  }

  /**
   * Gets the SFU peer ID.
   *
   * @returns The ID of the SFU peer, or undefined if not determined yet.
   */
  private getSFUPeerId(): string | undefined {
    if (!this.zeroHub || !this.zeroHub.myPeerId) {
      return undefined;
    }

    // If explicitly set, return it
    if (this.sfuPeerId) {
      return this.sfuPeerId;
    }

    // Otherwise, determine the lowest peer ID
    const allPeerIds = Object.keys(this.zeroHub.peers);
    if (allPeerIds.length === 0) {
      return this.zeroHub.myPeerId;
    }

    return this.lowestPeerId([this.zeroHub.myPeerId, ...allPeerIds]);
  }

  onPeerStatusChange(peer: Peer<PeerMetadata>) {
    if (!this.zeroHub || !this.zeroHub.myPeerId) {
      throw new Error("ZeroHub is not initialized");
    }

    const iAmSFU = this.isSFU();
    const sfuPeerId = this.getSFUPeerId();
    const peerIsSFU = peer.id === sfuPeerId;

    switch (peer.status) {
      case PeerStatus.Connected:
        if (iAmSFU) {
          this.zeroHub.logger.log(`SFU: Peer ${peer.id} connected`);
        }
        break;

      case PeerStatus.Pending:
        // Determine connection pattern based on SFU role
        if (iAmSFU) {
          // I am the SFU - I connect to all peers
          this.setupSFUConnection(peer);
        } else if (peerIsSFU) {
          // The peer is the SFU - connect to it
          this.setupClientToSFUConnection(peer);
        } else {
          // Neither is SFU - no direct connection needed in SFU topology
          // Regular clients don't connect to each other, only to the SFU
          this.zeroHub.logger.log(
            `Skipping connection between non-SFU peers: ${this.zeroHub.myPeerId} and ${peer.id}`
          );
          return;
        }
        break;

      case PeerStatus.ZeroHubDisconnected:
        if (peerIsSFU) {
          this.zeroHub.logger.warn("SFU peer disconnected - topology may fail");
          // In a production scenario, you might want to elect a new SFU here
        }
        break;

      case PeerStatus.Disconnected:
        // local client has torn down all peer connections; nothing to do
        break;
    }
  }

  /**
   * Sets up a connection where this peer (the SFU) connects to a client peer.
   * The SFU receives media from the client and can forward it to other clients.
   *
   * @param peer - The client peer to connect to.
   */
  private setupSFUConnection(peer: Peer<PeerMetadata>) {
    if (!this.zeroHub) {
      return;
    }

    this.zeroHub.logger.log(`SFU: Setting up connection to client ${peer.id}`);

    // SFU creates the offer, so it is always the offerer
    setupDataChannel(this.zeroHub.config, peer, true);

    // Set up media channels if configured
    setupMediaChannel(this.zeroHub.config, peer, undefined, (logger, peer) => {
      // In a full SFU implementation, you would forward this track to other peers here
      // For now, we just notify via the callback
      logger.log(`SFU: Received track from client ${peer.id}`);
    });

    // Send the offer
    this.zeroHub
      .sendOffer(peer.id, this.zeroHub.config.rtcOfferOptions)
      .catch((err) => {
        this.zeroHub?.logger.error(
          "SFU: Failed to send offer to client",
          peer.id,
          err
        );
      });
  }

  /**
   * Sets up a connection where this peer (a client) connects to the SFU.
   * The client sends its media to the SFU and receives forwarded media from the SFU.
   *
   * @param peer - The SFU peer to connect to.
   */
  private setupClientToSFUConnection(peer: Peer<PeerMetadata>) {
    if (!this.zeroHub) {
      return;
    }

    this.zeroHub.logger.log("Client: Connecting to SFU");

    // Client is the answerer (SFU creates the offer)
    setupDataChannel(this.zeroHub.config, peer, false);

    // Set up media channels if configured
    setupMediaChannel(
      this.zeroHub.config,
      peer,
      (logger, peer) => {
        logger.log(`Client: Sending track to SFU for peer ${peer.id}`);
      },
      (logger, peer) => {
        logger.log(`Client: Received track from SFU for peer ${peer.id}`);
      }
    );

    // Client waits for offer from SFU (doesn't initiate)
    // The offer will come through the signaling and trigger autoAnswer
  }
}
