version: "3.9"
services:
  service-app:
    container_name: zerohub
    image: hotcode/zerohub:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure

  service-redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: on-failure
