version: "3.9"
services:
  service-app:
    container_name: zero-hub
    image: ntsd/zero-hub:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
