version: "3.9"
services:
  service-app:
    container_name: zerohub
    image: hotcode/zerohub:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
