# fly.toml app configuration file generated for zero-hub-cold-star-3258 on 2024-01-27T14:31:46+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zero-hub'
primary_region = 'sin'

[build]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8080
    
[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
