// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.3
// source: proto/zerohub/v1/server_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Peer includes peer infomation and peer metadata
type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the peer
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata associated with the peer
	Metadata string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Time when the peer joined
	JoinTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Peer) GetJoinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinTime
	}
	return nil
}

// HubInfoMessage includes hub infomation
type HubInfoMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the hub
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Time when the hub was created
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Peer ID of the client
	MyPeerId string `protobuf:"bytes,3,opt,name=my_peer_id,json=myPeerId,proto3" json:"my_peer_id,omitempty"`
	// Metadata associated with the hub
	HubMetadata string `protobuf:"bytes,4,opt,name=hub_metadata,json=hubMetadata,proto3" json:"hub_metadata,omitempty"`
	// List of peers in the hub
	Peers         []*Peer `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubInfoMessage) Reset() {
	*x = HubInfoMessage{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubInfoMessage) ProtoMessage() {}

func (x *HubInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubInfoMessage.ProtoReflect.Descriptor instead.
func (*HubInfoMessage) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{1}
}

func (x *HubInfoMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HubInfoMessage) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *HubInfoMessage) GetMyPeerId() string {
	if x != nil {
		return x.MyPeerId
	}
	return ""
}

func (x *HubInfoMessage) GetHubMetadata() string {
	if x != nil {
		return x.HubMetadata
	}
	return ""
}

func (x *HubInfoMessage) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// PeerJoinedMessage will send if a peer has joined
type PeerJoinedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer that has joined
	Peer          *Peer `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerJoinedMessage) Reset() {
	*x = PeerJoinedMessage{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerJoinedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerJoinedMessage) ProtoMessage() {}

func (x *PeerJoinedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerJoinedMessage.ProtoReflect.Descriptor instead.
func (*PeerJoinedMessage) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{2}
}

func (x *PeerJoinedMessage) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

// PeerDisconnectedMessage will send if a peer has left
type PeerDisconnectedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the peer that has disconnected
	PeerId        string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDisconnectedMessage) Reset() {
	*x = PeerDisconnectedMessage{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDisconnectedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDisconnectedMessage) ProtoMessage() {}

func (x *PeerDisconnectedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDisconnectedMessage.ProtoReflect.Descriptor instead.
func (*PeerDisconnectedMessage) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{3}
}

func (x *PeerDisconnectedMessage) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// OfferMessage is sent offer SDP from offering peer to answer peer
type OfferMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the offering peer
	OfferPeerId string `protobuf:"bytes,1,opt,name=offer_peer_id,json=offerPeerId,proto3" json:"offer_peer_id,omitempty"`
	// SDP offer from the offering peer
	OfferSdp      string `protobuf:"bytes,2,opt,name=offer_sdp,json=offerSdp,proto3" json:"offer_sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferMessage) Reset() {
	*x = OfferMessage{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferMessage) ProtoMessage() {}

func (x *OfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferMessage.ProtoReflect.Descriptor instead.
func (*OfferMessage) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{4}
}

func (x *OfferMessage) GetOfferPeerId() string {
	if x != nil {
		return x.OfferPeerId
	}
	return ""
}

func (x *OfferMessage) GetOfferSdp() string {
	if x != nil {
		return x.OfferSdp
	}
	return ""
}

// AnswerMessage is sent answer SDP from answer peer to offering peer
type AnswerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the answering peer
	AnswerPeerId string `protobuf:"bytes,1,opt,name=answer_peer_id,json=answerPeerId,proto3" json:"answer_peer_id,omitempty"`
	// SDP answer from the answering peer
	AnswerSdp     string `protobuf:"bytes,2,opt,name=answer_sdp,json=answerSdp,proto3" json:"answer_sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerMessage) Reset() {
	*x = AnswerMessage{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerMessage) ProtoMessage() {}

func (x *AnswerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerMessage.ProtoReflect.Descriptor instead.
func (*AnswerMessage) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{5}
}

func (x *AnswerMessage) GetAnswerPeerId() string {
	if x != nil {
		return x.AnswerPeerId
	}
	return ""
}

func (x *AnswerMessage) GetAnswerSdp() string {
	if x != nil {
		return x.AnswerSdp
	}
	return ""
}

// IceCandidateMessage is not using yet
type IceCandidateMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the peer
	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// ICE candidate information
	Candidate     string `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IceCandidateMessage) Reset() {
	*x = IceCandidateMessage{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidateMessage) ProtoMessage() {}

func (x *IceCandidateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidateMessage.ProtoReflect.Descriptor instead.
func (*IceCandidateMessage) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{6}
}

func (x *IceCandidateMessage) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *IceCandidateMessage) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

// ServerMessage is the message sent from server
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_HubInfoMessage
	//	*ServerMessage_PeerJoinedMessage
	//	*ServerMessage_PeerDisconnectedMessage
	//	*ServerMessage_OfferMessage
	//	*ServerMessage_AnswerMessage
	//	*ServerMessage_IceCandidateMessage
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerohub_v1_server_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_zerohub_v1_server_message_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetHubInfoMessage() *HubInfoMessage {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_HubInfoMessage); ok {
			return x.HubInfoMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetPeerJoinedMessage() *PeerJoinedMessage {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_PeerJoinedMessage); ok {
			return x.PeerJoinedMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetPeerDisconnectedMessage() *PeerDisconnectedMessage {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_PeerDisconnectedMessage); ok {
			return x.PeerDisconnectedMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetOfferMessage() *OfferMessage {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_OfferMessage); ok {
			return x.OfferMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetAnswerMessage() *AnswerMessage {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_AnswerMessage); ok {
			return x.AnswerMessage
		}
	}
	return nil
}

func (x *ServerMessage) GetIceCandidateMessage() *IceCandidateMessage {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_IceCandidateMessage); ok {
			return x.IceCandidateMessage
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_HubInfoMessage struct {
	// Hub information message
	HubInfoMessage *HubInfoMessage `protobuf:"bytes,1,opt,name=hub_info_message,json=hubInfoMessage,proto3,oneof"`
}

type ServerMessage_PeerJoinedMessage struct {
	// Peer joined message
	PeerJoinedMessage *PeerJoinedMessage `protobuf:"bytes,2,opt,name=peer_joined_message,json=peerJoinedMessage,proto3,oneof"`
}

type ServerMessage_PeerDisconnectedMessage struct {
	// Peer disconnected message
	PeerDisconnectedMessage *PeerDisconnectedMessage `protobuf:"bytes,3,opt,name=peer_disconnected_message,json=peerDisconnectedMessage,proto3,oneof"`
}

type ServerMessage_OfferMessage struct {
	// Offer message
	OfferMessage *OfferMessage `protobuf:"bytes,4,opt,name=offer_message,json=offerMessage,proto3,oneof"`
}

type ServerMessage_AnswerMessage struct {
	// Answer message
	AnswerMessage *AnswerMessage `protobuf:"bytes,5,opt,name=answer_message,json=answerMessage,proto3,oneof"`
}

type ServerMessage_IceCandidateMessage struct {
	// ICE candidate message
	IceCandidateMessage *IceCandidateMessage `protobuf:"bytes,6,opt,name=ice_candidate_message,json=iceCandidateMessage,proto3,oneof"`
}

func (*ServerMessage_HubInfoMessage) isServerMessage_Message() {}

func (*ServerMessage_PeerJoinedMessage) isServerMessage_Message() {}

func (*ServerMessage_PeerDisconnectedMessage) isServerMessage_Message() {}

func (*ServerMessage_OfferMessage) isServerMessage_Message() {}

func (*ServerMessage_AnswerMessage) isServerMessage_Message() {}

func (*ServerMessage_IceCandidateMessage) isServerMessage_Message() {}

var File_proto_zerohub_v1_server_message_proto protoreflect.FileDescriptor

var file_proto_zerohub_v1_server_message_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x7a,
	0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x04, 0x50, 0x65,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x37,
	0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6a,
	0x6f, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x0e, 0x48, 0x75, 0x62, 0x49,
	0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x0a, 0x6d, 0x79, 0x5f, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x79, 0x50,
	0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x75, 0x62, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x75, 0x62,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x22, 0x3f, 0x0a, 0x11, 0x50, 0x65, 0x65, 0x72, 0x4a, 0x6f,
	0x69, 0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x70,
	0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x17, 0x50, 0x65, 0x65, 0x72, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x0c, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x73, 0x64, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x64, 0x70, 0x22, 0x54, 0x0a, 0x0d,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x50, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x73, 0x64,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x53,
	0x64, 0x70, 0x22, 0x4c, 0x0a, 0x13, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x96, 0x04, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x4c, 0x0a, 0x10, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x0e, 0x68, 0x75, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x55, 0x0a, 0x13, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x65, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x11, 0x70, 0x65, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x67, 0x0a, 0x19, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65,
	0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x17, 0x70, 0x65, 0x65, 0x72, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x45, 0x0a, 0x0d, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x48, 0x0a, 0x0e, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x0d, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x5b, 0x0a, 0x15, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x13, 0x69, 0x63, 0x65, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x56, 0x0a, 0x14, 0x63, 0x6f, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2e, 0x76,
	0x31, 0x42, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x64, 0x65, 0x76, 0x2f,
	0x7a, 0x65, 0x72, 0x6f, 0x68, 0x75, 0x62, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_zerohub_v1_server_message_proto_rawDescOnce sync.Once
	file_proto_zerohub_v1_server_message_proto_rawDescData = file_proto_zerohub_v1_server_message_proto_rawDesc
)

func file_proto_zerohub_v1_server_message_proto_rawDescGZIP() []byte {
	file_proto_zerohub_v1_server_message_proto_rawDescOnce.Do(func() {
		file_proto_zerohub_v1_server_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_zerohub_v1_server_message_proto_rawDescData)
	})
	return file_proto_zerohub_v1_server_message_proto_rawDescData
}

var file_proto_zerohub_v1_server_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_zerohub_v1_server_message_proto_goTypes = []any{
	(*Peer)(nil),                    // 0: proto.zerohub.v1.Peer
	(*HubInfoMessage)(nil),          // 1: proto.zerohub.v1.HubInfoMessage
	(*PeerJoinedMessage)(nil),       // 2: proto.zerohub.v1.PeerJoinedMessage
	(*PeerDisconnectedMessage)(nil), // 3: proto.zerohub.v1.PeerDisconnectedMessage
	(*OfferMessage)(nil),            // 4: proto.zerohub.v1.OfferMessage
	(*AnswerMessage)(nil),           // 5: proto.zerohub.v1.AnswerMessage
	(*IceCandidateMessage)(nil),     // 6: proto.zerohub.v1.IceCandidateMessage
	(*ServerMessage)(nil),           // 7: proto.zerohub.v1.ServerMessage
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_proto_zerohub_v1_server_message_proto_depIdxs = []int32{
	8,  // 0: proto.zerohub.v1.Peer.join_time:type_name -> google.protobuf.Timestamp
	8,  // 1: proto.zerohub.v1.HubInfoMessage.create_time:type_name -> google.protobuf.Timestamp
	0,  // 2: proto.zerohub.v1.HubInfoMessage.peers:type_name -> proto.zerohub.v1.Peer
	0,  // 3: proto.zerohub.v1.PeerJoinedMessage.peer:type_name -> proto.zerohub.v1.Peer
	1,  // 4: proto.zerohub.v1.ServerMessage.hub_info_message:type_name -> proto.zerohub.v1.HubInfoMessage
	2,  // 5: proto.zerohub.v1.ServerMessage.peer_joined_message:type_name -> proto.zerohub.v1.PeerJoinedMessage
	3,  // 6: proto.zerohub.v1.ServerMessage.peer_disconnected_message:type_name -> proto.zerohub.v1.PeerDisconnectedMessage
	4,  // 7: proto.zerohub.v1.ServerMessage.offer_message:type_name -> proto.zerohub.v1.OfferMessage
	5,  // 8: proto.zerohub.v1.ServerMessage.answer_message:type_name -> proto.zerohub.v1.AnswerMessage
	6,  // 9: proto.zerohub.v1.ServerMessage.ice_candidate_message:type_name -> proto.zerohub.v1.IceCandidateMessage
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_zerohub_v1_server_message_proto_init() }
func file_proto_zerohub_v1_server_message_proto_init() {
	if File_proto_zerohub_v1_server_message_proto != nil {
		return
	}
	file_proto_zerohub_v1_server_message_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_HubInfoMessage)(nil),
		(*ServerMessage_PeerJoinedMessage)(nil),
		(*ServerMessage_PeerDisconnectedMessage)(nil),
		(*ServerMessage_OfferMessage)(nil),
		(*ServerMessage_AnswerMessage)(nil),
		(*ServerMessage_IceCandidateMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_zerohub_v1_server_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_zerohub_v1_server_message_proto_goTypes,
		DependencyIndexes: file_proto_zerohub_v1_server_message_proto_depIdxs,
		MessageInfos:      file_proto_zerohub_v1_server_message_proto_msgTypes,
	}.Build()
	File_proto_zerohub_v1_server_message_proto = out.File
	file_proto_zerohub_v1_server_message_proto_rawDesc = nil
	file_proto_zerohub_v1_server_message_proto_goTypes = nil
	file_proto_zerohub_v1_server_message_proto_depIdxs = nil
}
