// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: proto/client_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendOfferMessage is sent offer SDP from offering peer to answer peer
type SendOfferMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnswerPeerID uint32 `protobuf:"varint,1,opt,name=answerPeerID,proto3" json:"answerPeerID,omitempty"`
	OfferSDP     string `protobuf:"bytes,2,opt,name=offerSDP,proto3" json:"offerSDP,omitempty"`
}

func (x *SendOfferMessage) Reset() {
	*x = SendOfferMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_client_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOfferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOfferMessage) ProtoMessage() {}

func (x *SendOfferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOfferMessage.ProtoReflect.Descriptor instead.
func (*SendOfferMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendOfferMessage) GetAnswerPeerID() uint32 {
	if x != nil {
		return x.AnswerPeerID
	}
	return 0
}

func (x *SendOfferMessage) GetOfferSDP() string {
	if x != nil {
		return x.OfferSDP
	}
	return ""
}

// SendAnswerMessage is sent answer SDP from answer peer to offering peer
type SendAnswerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfferPeerID uint32 `protobuf:"varint,1,opt,name=offerPeerID,proto3" json:"offerPeerID,omitempty"`
	AnswerSDP   string `protobuf:"bytes,2,opt,name=answerSDP,proto3" json:"answerSDP,omitempty"`
}

func (x *SendAnswerMessage) Reset() {
	*x = SendAnswerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_client_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAnswerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAnswerMessage) ProtoMessage() {}

func (x *SendAnswerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAnswerMessage.ProtoReflect.Descriptor instead.
func (*SendAnswerMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendAnswerMessage) GetOfferPeerID() uint32 {
	if x != nil {
		return x.OfferPeerID
	}
	return 0
}

func (x *SendAnswerMessage) GetAnswerSDP() string {
	if x != nil {
		return x.AnswerSDP
	}
	return ""
}

// SendICECandidateMessage is not using yet
type SendICECandidateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerID    uint32 `protobuf:"varint,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Candidate string `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
}

func (x *SendICECandidateMessage) Reset() {
	*x = SendICECandidateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_client_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendICECandidateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendICECandidateMessage) ProtoMessage() {}

func (x *SendICECandidateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendICECandidateMessage.ProtoReflect.Descriptor instead.
func (*SendICECandidateMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendICECandidateMessage) GetPeerID() uint32 {
	if x != nil {
		return x.PeerID
	}
	return 0
}

func (x *SendICECandidateMessage) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

// ClientMessage is the message sent from client
type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ClientMessage_OfferMessage
	//	*ClientMessage_AnswerMessage
	//	*ClientMessage_SendICECandidate
	Message isClientMessage_Message `protobuf_oneof:"message"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_client_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_client_message_proto_rawDescGZIP(), []int{3}
}

func (m *ClientMessage) GetMessage() isClientMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ClientMessage) GetOfferMessage() *SendOfferMessage {
	if x, ok := x.GetMessage().(*ClientMessage_OfferMessage); ok {
		return x.OfferMessage
	}
	return nil
}

func (x *ClientMessage) GetAnswerMessage() *SendAnswerMessage {
	if x, ok := x.GetMessage().(*ClientMessage_AnswerMessage); ok {
		return x.AnswerMessage
	}
	return nil
}

func (x *ClientMessage) GetSendICECandidate() *SendICECandidateMessage {
	if x, ok := x.GetMessage().(*ClientMessage_SendICECandidate); ok {
		return x.SendICECandidate
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_OfferMessage struct {
	OfferMessage *SendOfferMessage `protobuf:"bytes,2,opt,name=offerMessage,proto3,oneof"`
}

type ClientMessage_AnswerMessage struct {
	AnswerMessage *SendAnswerMessage `protobuf:"bytes,3,opt,name=answerMessage,proto3,oneof"`
}

type ClientMessage_SendICECandidate struct {
	SendICECandidate *SendICECandidateMessage `protobuf:"bytes,4,opt,name=sendICECandidate,proto3,oneof"`
}

func (*ClientMessage_OfferMessage) isClientMessage_Message() {}

func (*ClientMessage_AnswerMessage) isClientMessage_Message() {}

func (*ClientMessage_SendICECandidate) isClientMessage_Message() {}

var File_proto_client_message_proto protoreflect.FileDescriptor

var file_proto_client_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x10,
	0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x50, 0x65,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x44, 0x50,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x44, 0x50,
	0x22, 0x53, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x50, 0x65,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6f, 0x66, 0x66, 0x65,
	0x72, 0x50, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x53, 0x44, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x53, 0x44, 0x50, 0x22, 0x4f, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x43, 0x45,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0xd7, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x6f, 0x66, 0x66, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x0c, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0d,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x46, 0x0a,
	0x10, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x43,
	0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68,
	0x6f, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x68,
	0x75, 0x62, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_client_message_proto_rawDescOnce sync.Once
	file_proto_client_message_proto_rawDescData = file_proto_client_message_proto_rawDesc
)

func file_proto_client_message_proto_rawDescGZIP() []byte {
	file_proto_client_message_proto_rawDescOnce.Do(func() {
		file_proto_client_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_client_message_proto_rawDescData)
	})
	return file_proto_client_message_proto_rawDescData
}

var file_proto_client_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_client_message_proto_goTypes = []interface{}{
	(*SendOfferMessage)(nil),        // 0: SendOfferMessage
	(*SendAnswerMessage)(nil),       // 1: SendAnswerMessage
	(*SendICECandidateMessage)(nil), // 2: SendICECandidateMessage
	(*ClientMessage)(nil),           // 3: ClientMessage
}
var file_proto_client_message_proto_depIdxs = []int32{
	0, // 0: ClientMessage.offerMessage:type_name -> SendOfferMessage
	1, // 1: ClientMessage.answerMessage:type_name -> SendAnswerMessage
	2, // 2: ClientMessage.sendICECandidate:type_name -> SendICECandidateMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_client_message_proto_init() }
func file_proto_client_message_proto_init() {
	if File_proto_client_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_client_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOfferMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_client_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAnswerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_client_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendICECandidateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_client_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_client_message_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ClientMessage_OfferMessage)(nil),
		(*ClientMessage_AnswerMessage)(nil),
		(*ClientMessage_SendICECandidate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_client_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_client_message_proto_goTypes,
		DependencyIndexes: file_proto_client_message_proto_depIdxs,
		MessageInfos:      file_proto_client_message_proto_msgTypes,
	}.Build()
	File_proto_client_message_proto = out.File
	file_proto_client_message_proto_rawDesc = nil
	file_proto_client_message_proto_goTypes = nil
	file_proto_client_message_proto_depIdxs = nil
}
