name: bump package version
on:
  workflow_dispatch:
    inputs:
      package:
        description: "The package to bump the version of"
        required: true
        default: "@salary-hero/typedef"
      version:
        description: "The version to bump to"
        required: true
        default: "latest"
jobs:
  manual-bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
